use std::collections::HashSet;

// Determine whether a sentence is a pangram.
pub fn is_pangram(sentence: &str) -> bool {
    // This a fourth  solution generated by Git Copilot.
    let mut letters = HashSet::new(); // Create a HashSet to store unique letters

    sentence.to_lowercase().chars() // Convert to lowercase and iterate over characters
        .filter(|c| c.is_ascii_alphabetic()) // Filter out non-alphabetic characters
        .for_each(|c| { letters.insert(c); }); // Insert the character into the HashSet

    
    letters.len() == 26 // Check if the number of unique letters is 26 (the number of letters in the English alphabet)
}