#[derive(Debug, PartialEq, Eq)]


// The derive attribute is used to import the PartialEq trait - it also needs the Eq trait, so that's imported as well

pub enum Comparison {
    Equal,
    Sublist,
    Superlist,
    Unequal,
}

// As I couldn't figure out the best method of doing this myself, I looked at what others had done and found this.
// So I thought I would document the solution I found -- Credit to jixxx
// There is a lot going on, so there are a lot of comments for a couple of the lines of code 


pub fn sublist<T: PartialEq>(_first_list: &[T], _second_list: &[T]) -> Comparison {   // Function declaration 
            // T: PartialEq - requires the arbitrary type to implement the PartialEq trait
                            //  first_list & second_lists are  slices of to the same arbitrary type
                                                                   // Returns a Comparison object,     
    let sublist = _first_list.is_empty() || 
        _second_list.windows(_first_list.len()).any(|x| x == _first_list);
// If the first_list is empty, then it can't be a superlist, nor can it be unequal
        //  _second_list.windows is an iterator.  Each iteration is a sublist of _second_list and the argument _first_list.len() means each sublist is as long as _first_list.
        //  For the any method - the | x | defines x as a label for the current iterator, and this tested against the first_list by 'X==_first_list'
        //  The any method returns 'true' if one iterator satisfies the condition.
        // So the overall effect os this line is that a number of slices from second_list are generated by windows method, 
        // and each is tested against the _first_list.  If a match is found, then 'true' is returned.  If no match, or if the first_list is longer than second_list,
        // then false is returnd.
        
    let superlist = _second_list.is_empty() ||
        _first_list.windows(_second_list.len()).any(|x| x == _second_list);
    // This statement applied the same logic ast the statement above, but with the lists reversed.

    match (sublist, superlist) {
        (true, true) => Comparison::Equal,
        (true, false) => Comparison::Sublist,
        (false, true) => Comparison::Superlist,
        (false, false) => Comparison::Unequal,
    }
    // This match statement generates the return value based on the values of sublist & superlist - 
}

